version: '2'

volumes:
  postgres_data_develop: {}
  postgres_backup_develop: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_develop:/var/lib/postgresql/data
      - postgres_backup_develop:/backups
    environment:
      - POSTGRES_USER=python-project
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=python-project
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres




