version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./compose/postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env
    depends_on:
      - nginx-proxy
    ports:
      - "5432:5432"
    environment:
      - "VIRTUAL_HOST=postgres"
      - "VIRTUAL_PORT=5432"

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - "VIRTUAL_HOST=redis"
      - "VIRTUAL_PORT=6379"

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
