# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-15 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la categoria')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la categoria')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Necesidad',
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dia')),
                ('time', models.TimeField(verbose_name='Hora de atencion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('Cancelada', 'Cancelada'), ('Asignada', 'Asignada')], default='Asignada', max_length=255, verbose_name='Estado de la peticion')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Need', verbose_name='Necesidad')),
                ('shedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.Shedule', verbose_name='Horario')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Peticion',
            },
        ),
    ]
