# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Ciudades'},
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Cancelada', 'Cancelada'), ('Funcionario', 'Funcionario')], default='Funcionario', max_length=255, verbose_name='Rol'),
        ),
    ]
