# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170815_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Funcionario', 'Funcionario')], default='Funcionario', max_length=255, verbose_name='Rol'),
        ),
    ]
