FROM python:3.5

ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

COPY ./compose/django/entrypoint-dev.sh /entrypoint-dev.sh
RUN sed -i 's/\r//' /entrypoint-dev.sh
RUN chmod +x /entrypoint-dev.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint-dev.sh"]
